# Generated by Django 5.2.7 on 2025-10-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('qty', models.IntegerField(default=0)),
                ('price', models.FloatField(default=1.0)),
            ],
        ),
    ]
